# Generated by Django 5.2.1 on 2025-06-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'mainapp_customer',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('salt', models.BinaryField()),
                ('password_hash', models.CharField(max_length=256)),
                ('previous_password_hash1', models.CharField(blank=True, max_length=256)),
                ('previous_password_hash2', models.CharField(blank=True, max_length=256)),
                ('previous_password_hash3', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'mainapp_user',
            },
        ),
    ]
