# Generated by Django 5.2 on 2025-05-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_package_user_previous_password_hash1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
