# Generated by Django 5.2.1 on 2025-05-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_customer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='package',
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='previous_password_hash1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='previous_password_hash2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='previous_password_hash3',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='mainapp_customer',
        ),
        migrations.AlterModelTable(
            name='user',
            table='mainapp_package',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
